jeka.version=0.11.59
jeka.java.version=21

jeka.kbean.default=project

# Use a build convention defined at https://github.com/jeka-dev/demo-build-templates
jeka.classpath=dev.jeka:convention-examples:0.11.39-2
@convention=on

@native.metadataRepoVersion=0.10.6



